import type { Metadata } from "next";
import "@mpesaflow/ui/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { PHProvider } from "@mpesaflow/analytics";
import MainNav from "../components/main-nav";

export const metadata: Metadata = {
  title: "MpesaFlow | Powering Payments for Developers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <PHProvider>
          <body className="flex flex-col min-h-screen antialiased w-full bg-background text-foreground">
            <MainNav />
            <div>{children}</div>
          </body>
        </PHProvider>
      </ClerkProvider>
    </html>
  );
}
